Patch set applies cleanly to Linux 4.4.35

diff --git a/apply-patches b/apply-patches
--- a/apply-patches
+++ b/apply-patches
@@ -154,7 +154,15 @@ apply_patches()
 						exit 1
 					fi
 					printf '%s\n' "INFO: Applying patch file '$patchRelativeFilePath' from line (one-based) $lineNumber" 1>&2
+					set +e
 					patch -p1 -i "$ourFolderPath"/patches/"$patchRelativeFilePath" 1>&2
+					local exitCode=$?
+					set -e
+					
+					if [ $exitCode -ne 0 ]; then
+						printf '\n\nPATCHING FAILED for %s (exit code was %s)\n\n' "$patchRelativeFilePath" "$exitCode" 1>&2
+						exit 1
+					fi
 				;;
 			
 			esac
@@ -163,6 +171,9 @@ apply_patches()
 		done <"$patchSeriesFilePath"
 		
 	cd - 1>/dev/null 2>/dev/null
+	
+	printf '\nUnapply patches with git reset --hard && git clean -f -d -x %s\n' "$linuxStableFolderPath" 1>&2
+	printf '\n\nALL PATCHES APPLIED\n\n' 1>&2
 }
 
 apply_patches "$@"
